### ISSUE TITLE
Implement lazy loading to the pages

### ISSUE THREAD

**Issue by Avinash905** [abhijeet141/CropForesight-FrontEnd#100]
### Description

Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by abhijeet141** [comment]
Hi @Avinash905 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
