### ISSUE TITLE
Convert Images to WebP Format for Improved Project Performance

### ISSUE THREAD

**Issue by Avinash905** [abhijeet141/CropForesight-FrontEnd#101]
### Description

Currently, the images in the project are stored in the PNG/JPG image format. However, I would like to convert them to the more efficient WebP format. This conversion will help us reduce file sizes while maintaining image quality, leading to improved website performance and faster loading times. This issue aims to update the entire project's image assets from PNG/JPG to WebP format.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by abhijeet141** [comment]
Hi @Avinash905 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
