### ISSUE TITLE
Website does not have proper meta tags

### ISSUE THREAD

**Issue by Avinash905** [abhijeet141/CropForesight-FrontEnd#102]
**Issue:** The website does not have important meta tags.

**Impact:** This means that the website is not as visible in search results, and users are less likely to click on the website's links.

**Resolution:** The website should contain important meta tags. This will help the website rank higher in search results and attract more visitors.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by abhijeet141** [comment]
Hi @Avinash905 
Thank you for creating this issue but this issue has already been resolved.

**Comment by Avinash905** [comment]
@abhijeet141 The website does not have tags like open graph and twitter which are displayed when you share on any social media.

**Comment by Avinash905** [comment]
@abhijeet141 The website does not contain meta tags like open graph and twitter tags which are displayed when you share on any social media.

**Comment by abhijeet141** [comment]
> @abhijeet141 The website does not have tags like open graph and twitter which are displayed when you share on any social media.

@Avinash905 Okay
