### ISSUE TITLE
Improve the Contact Page

### ISSUE THREAD

**Issue by abhinav-m22** [abhijeet141/CropForesight-FrontEnd#106]
The contact page has alignment issues as seen in the screenshot below.
Also the page looks very simple.

<br />

I will add hover animations as well as fading effects to the page to make it visually appealing.
Also I will add appropriate links to the social icons given.
<br />

I want to work on this issue.
Please assign me the task under GSSoC'23.

<img width="960" alt="image" src="https://github.com/abhijeet141/CropForesight-FrontEnd/assets/113239388/71d84969-1177-4af2-8103-4a934f8714f5">

**Comment by abhijeet141** [comment]
Hi @abhinav-m22 
Thank you for creating this issue but this issue is already resolved.
