### ISSUE TITLE
Weather section `Upgrading UI`

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [abhijeet141/CropForesight-FrontEnd#107]
Hello Project Admin,
Weather section is not working.

Please assign me  this so I can start working on this and will make the UI and the functionality more stronger. 💯 

### Issue Screenshot - 
![Screenshot from 2023-06-23 13-49-43](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/121503426/1eea4139-a279-428d-b155-8c160c9b478a)

**Comment by abhijeet141** [comment]
Hi @SyedImtiyaz-1 Check once now Its working fine for me

**Comment by SyedImtiyaz-1** [comment]
@abhijeet141 ,
Yeah it's working  💯 
but the UI is not looking that cool can you please assign me so I can upgrade the  UI

**Comment by abhijeet141** [comment]
@SyedImtiyaz-1 Yeah actually one of the contributor is already working on the UI please wait for some time if there will be no response I will assign this issue to you

**Comment by SyedImtiyaz-1** [comment]
> @SyedImtiyaz-1 You can start working on this issue now

Thank You.
