### ISSUE TITLE
Add hover effect on predict your crop button.

### ISSUE THREAD

**Issue by akshaysoni10** [abhijeet141/CropForesight-FrontEnd#109]
I want to add hover effect on predict your crop, get in touch and send button so it's look more attractive.

**Comment by akshaysoni10** [comment]
Add hover effect.

**Comment by abhijeet141** [comment]
Hi @akshaysoni10 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue

**Comment by akshaysoni10** [comment]
Thank you @abhijeet141 for assigning me this task. I will try to merge PR very soon.
