### ISSUE TITLE
Adding more attributes about the weather information and make it more attractive #GSSOC'2023

### ISSUE THREAD

**Issue by Jay-Shinde** [abhijeet141/CropForesight-FrontEnd#112]
### I would like to design the weather info page and add more attributes to it. 

kind of this design :
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/90144181/5fb5bc35-2cf9-43af-ba65-3c4ba33e964e)

Kindly assign this issue to me .

**Comment by abhijeet141** [comment]
Hi @Jay-Shinde Thank you for creating the issue but this issue is already assigned #114 if after his PR is merged you think you can add more attributes just message here I will assign you

**Comment by Jay-Shinde** [comment]
Sure.
I'll definitely contribute if required further.

**Comment by Jay-Shinde** [comment]
Hello @abhijeet141 
May I work on this issue now ?
