### ISSUE TITLE
refining the Crop Prediction card and Predict Your Crop button responsiveness in mobile view.

### ISSUE THREAD

**Issue by Jay-Shinde** [abhijeet141/CropForesight-FrontEnd#113]
**Hello sir, 
I would like to add responsiveness to the mentioned elements as in the mobile view the card is changing its height on changing text in it.**

**Comment by abhijeet141** [comment]
Hi @Jay-Shinde 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue

**Comment by Jay-Shinde** [comment]
Thank you @abhijeet141 
for assigning this issue to me !

**Comment by Jay-Shinde** [comment]
Hii @abhijeet141  sir,
It is showing "**This branch has conflicts that must be resolved**"
and also a **resolve conflicts** button

can you please explain, what am I supposed to do

**Comment by abhijeet141** [comment]
@Jay-Shinde, Please don't call me sir , don't worry I will resolve the conflicts.
