### ISSUE TITLE
Adding a preloading screen

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight-FrontEnd#119]
Hey, I want to add a preloading screen before the page is loaded.
Can you please assign this issue to me ?

**Comment by abhijeet141** [comment]
Hi @SubhamB2003 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
