### ISSUE TITLE
Contact page UI Improcement

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight-FrontEnd#125]
@abhijeet141 Hey, I want to change the contact form UI its needs some improvement and I also changed the horizontal scrollbar

Previous
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/a98161d6-c77a-4fe2-9ca3-d345650358f4)

After
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/56dda46d-e9c0-4f0b-bbf2-a3145e9fb4a6)

Scrollbar
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/7f60b1f3-7edb-4772-a186-34f7acdc551e)

**Comment by abhijeet141** [comment]
Hi @SubhamB2003 
Thank you for creating this issue but this issue is already resolved and one of the contributor is working on the same issue

**Comment by SubhamB2003** [comment]
> 

Yeah ok
