### ISSUE TITLE
Enhance UI of the testimonial section.

### ISSUE THREAD

**Issue by Pragati-3003** [abhijeet141/CropForesight-FrontEnd#134]
I would like to enhance the UI of the testimonial section by adding cool effects .
So, please assign this issue to me under gssoc'23.
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/132778037/5191277d-6ddf-4e76-ae86-9e913ce68d86)

**Comment by abhijeet141** [comment]
Hi @Pragati-3003 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
