### ISSUE TITLE
Validation add on Crop form label not visible in white background

### ISSUE THREAD

**Issue by Geeta259** [abhijeet141/CropForesight-FrontEnd#135]
Empty validation add on crop form field before evaluating the form
label colour should be change some label not visible in form.
![Screenshot (449)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/75520947/457198eb-8f82-4f2f-a5ed-42921ab128f8)
@abhijeet141 I would like to contribute on this project under GSSOC'23

**Comment by abhijeet141** [comment]
Hi @Geeta259 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
