### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by karthiknadar1204** [abhijeet141/CropForesight-FrontEnd#140]
In the current readme, a new user might get confused as to how to open their first pr as it is still a bit vague.
In my solution, I propose to have the commands to open the pr as shell commands to make it easy for any new visitor for the project.

Also I though of adding the timeline for gssoc to the readme i.e the pointer system , like what kind of issues are level1 and level2 in a comprehensive manner.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by abhijeet141** [comment]
Hi @karthiknadar1204 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue

**Comment by karthiknadar1204** [comment]
Will push pr in a bit,thank you so much
