### ISSUE TITLE
[BUG]:  FAQ UI

### ISSUE THREAD

**Issue by anamika7153** [abhijeet141/CropForesight-FrontEnd#141]
I'm from GSSoC'23

FAQ page is not completely responsive.
I would like to make it responsive for different screen sizes.

<img width="460" alt="image" src="https://github.com/abhijeet141/CropForesight-FrontEnd/assets/66116440/fd2e60d7-ed8a-4c28-b9f6-d93c56a29418">

<img width="471" alt="image" src="https://github.com/abhijeet141/CropForesight-FrontEnd/assets/66116440/940e6189-b75c-4127-a18b-07a0c367956a">

**Comment by abhijeet141** [comment]
Hi @anamika7153 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue

**Comment by anamika7153** [comment]
@abhijeet141  Hey, you have not added level labels to it.
