### ISSUE TITLE
TO MAKE THE ABOUT PAGE RESPONSIVE 

### ISSUE THREAD

**Issue by adi10032003** [abhijeet141/CropForesight-FrontEnd#142]
Hello sir i want through your project and i am interested in making the changes in the about page the changes that i am going to make is that
1.Trying to make a good ui of it
2.Will improve its alignment
3.Adding show attractive design and improved responsiveness
Please issue it to me under gssoc
Will be waiting for your reply
Thank You

**Comment by abhijeet141** [comment]
Hi @adi10032003 
Thank you for creating the issue but this issue is already resolved now
