### ISSUE TITLE
Weather Page Alignment

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [abhijeet141/CropForesight-FrontEnd#147]
Hello @abhijeet141 ,
There is a issue in Weather Page.
## Screenshot - 
![Screenshot from 2023-06-28 03-02-29](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/121503426/1906b25c-3b64-4f53-86cf-6899f654e309)

### Please assign me this so I can fix this issue 👍🏻

**Comment by abhijeet141** [comment]
Hi @SyedImtiyaz-1 
Thank you for creating this issue but there is already contributor who is working on the same issue
