### ISSUE TITLE
Make a name Logo of the CropForesight Website

### ISSUE THREAD

**Issue by Tisha6661** [abhijeet141/CropForesight-FrontEnd#151]
As an active member of GSSOC'23, I would like to contribute in making the Website Logo, to present the site beautifully. Some of the logos I have designed are here, to let you know better and assign me this task.

![dark](https://github.com/abhijeet141/CropForesight_BackEnd/assets/98682478/e94449c1-7cd5-45b6-b861-49907d104d18)

![Screenshot 2023-06-24 005041](https://github.com/abhijeet141/CropForesight_BackEnd/assets/98682478/4a0d2a5a-e9bf-44e3-b3ac-1228d2dccd0f)

**Comment by Tisha6661** [comment]
@abhijeet141 Thank you for assigning me this task, please add the tag in the assignee too.

**Comment by Tisha6661** [comment]
@abhijeet141 I have created a pull request regarding this task, please verify and merge it.

**Comment by abhijeet141** [comment]
@Tisha6661 Done
