### ISSUE TITLE
Improve UI for the crop recommendation page.

### ISSUE THREAD

**Issue by Pragati-3003** [abhijeet141/CropForesight-FrontEnd#157]
I would like to change the UI for the crop recommendation page by adding some effects and by increasing visualizations.
So,please assign this task to me under gssoc'23
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/132778037/77e7ff52-5685-430b-9a4e-4c3e140cd2a5)

**Comment by abhijeet141** [comment]
Hi @Pragati-3003 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
