### ISSUE TITLE
Remove same duplicate element

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight-FrontEnd#158]
@abhijeet141 Hey, below the image same text occurs two times but it is not needed. So I want to remove it and also I want to change the vertical scrollbar design. Can you please assign it to me?

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/927325db-3f79-4c35-8f15-2c89d56381ea)

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/b00a77a3-e246-477f-8db7-08ef8b3db9b2)

**Comment by abhijeet141** [comment]
Hi @SubhamB2003 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
