### ISSUE TITLE
Modify Issues Template

### ISSUE THREAD

**Issue by parasss19** [abhijeet141/CropForesight-FrontEnd#160]
## Current
- There are no separate issues section for bug ,feature and documentation 
- So its tough for project admins to provide labels in issues

## Change
- I will write  all the code for  issues template in .yml format

### 1
<img width="880" alt="Screenshot 2023-06-20 232906" src="https://github.com/abhijeet141/CropForesight-FrontEnd/assets/101205226/fedabb4e-1719-49f2-b7f6-0120b0fdcf23">

### 2
<img width="721" alt="temp img" src="https://github.com/abhijeet141/CropForesight-FrontEnd/assets/101205226/24660ad2-cb05-4558-87ed-2aa859522f87">

### 3 
- I will also add important checkboxes in issues template
<img width="942" alt="Screenshot 2023-06-25 183208" src="https://github.com/abhijeet141/CropForesight-FrontEnd/assets/101205226/ee3a075f-bd43-4722-97ac-45d3c67fa2e3">

**Comment by abhijeet141** [comment]
Hi @parasss19 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
