### ISSUE TITLE
[Style]: Improve contact form

### ISSUE THREAD

**Issue by rishuraj1** [abhijeet141/CropForesight-FrontEnd#164]
The contact form is so plain right now,
For better user experience and look, we might need to add some icons and styles to the form according to the color and theme of page.

<img width="960" alt="image" src="https://github.com/abhijeet141/CropForesight-FrontEnd/assets/47839626/2b2f32aa-04aa-43a7-8e29-330fce26b372">

PS: I would really like to contribute to this project. Please assign this task to me under GSSoC '23. Thank You !

**Comment by abhijeet141** [comment]
Hi @rishuraj1 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
