### ISSUE TITLE
[Fix]: Improve Crop Predictor page

### ISSUE THREAD

**Issue by rishuraj1** [abhijeet141/CropForesight-FrontEnd#165]
We might need to improve the crop predictor page as it takes large height and we need to scroll to end to submit the form.
I want to contain it in maximum view height of screen.
I will help to get better user experience and look overall.

<img width="960" alt="image" src="https://github.com/abhijeet141/CropForesight-FrontEnd/assets/47839626/8619c017-6cc9-4acc-b044-f84976a3b4e5">

Please assign this task to me under GSSoC '23.
Thank You !

**Comment by abhijeet141** [comment]
Hi @rishuraj1 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
