### ISSUE TITLE
I want to add arrows for slider in testimonials 

### ISSUE THREAD

**Issue by I-shika** [abhijeet141/CropForesight-FrontEnd#168]
I want to add slider for testimonials for more user friendly experience.
![Screenshot (92)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/100770197/009b500d-dd2b-4cc1-89ed-b9f76cae5512)

Please assign this issue to me under GSSoC'23.

**Comment by abhijeet141** [comment]
Hi @I-shika 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue

**Comment by krutikajichkar** [comment]
@I-shika testimonial slider keeps on sliding and stops on hovering , so there is no such need for arrows . I have fixed this earlier
