### ISSUE TITLE
Fixing the font

### ISSUE THREAD

**Issue by kaur-rajdeep** [abhijeet141/CropForesight-FrontEnd#169]
Each page has different fonts, making it inconsistent to view. I would like to fix the font styles and size to make it look much better. Could you please assign me this issue under GSSOC'23 ? 
Thank you.

**Comment by abhijeet141** [comment]
Hi @kaur-rajdeep 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
