### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by akuldeepj** [abhijeet141/CropForesight-FrontEnd#17]
Since the webpage lacks a contact page I would like to create one can you assign me as a gssoc'23 contributor

**Comment by abhijeet141** [comment]
Hi @akuldeepj 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by akuldeepj** [comment]
hey @abhijeet141 I also Added a hover effect to navBar is it fine 
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/97216956/de05a955-ef91-453f-a7b8-d762c8aa766d)

**Comment by akuldeepj** [comment]
actually missed from the previous pull request
