### ISSUE TITLE
Example table ui improvement

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight-FrontEnd#173]
Hey, I want to improve the example table UI.

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/545c202b-0685-4175-b0b2-8494b3b39b3c)

**Comment by SubhamB2003** [comment]
@abhijeet141 Please assign it to me.
https://docs.google.com/spreadsheets/u/2/d/1DsO2zP5u3XCF-pFJMhrVKKQXCew3esEd-PQC1w8-Nro/edit?pli=1

**Comment by abhijeet141** [comment]
@SubhamB2003 As I can see it  is looking responsive
