### ISSUE TITLE
Upgrading UI of the Navbar

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [abhijeet141/CropForesight-FrontEnd#175]
Hello @abhijeet141 ,
The navbar is looking default and there is no padding and the font weight in the navbar can you please assign me so I can fix this issue.
### Screenshot - 
![Screenshot from 2023-07-05 23-19-48](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/121503426/58edf5ef-4751-4e1a-8396-7e488f2be3cd)

### Tab & Mobile Ratio - 
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/121503426/8f210e9d-6fc8-4c16-9823-a0284fe5ab53)

**Comment by abhijeet141** [comment]
Hi @SyedImtiyaz-1 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
