### ISSUE TITLE
Fix the responsiveness of the about Us page for mobile view.

### ISSUE THREAD

**Issue by abhi03ruchi** [abhijeet141/CropForesight-FrontEnd#186]
I would like to fix the responsiveness of the about Us page for mobile view , it is completely broken. 
The salient feature section is displayed twice. 

Issue : 
https://github.com/abhijeet141/CropForesight-FrontEnd/assets/105661636/311d34e4-dd04-4dc7-889b-d6fe78acdef8

Plz assign me this issue under gssoc'23.

**Comment by abhijeet141** [comment]
Hi @abhi03ruchi 
Thank you for creating the issue but this issue is already assigned https://github.com/abhijeet141/CropForesight-FrontEnd/issues/171
