### ISSUE TITLE
Code Refactor of different files.

### ISSUE THREAD

**Issue by AlfiyaSiddique** [abhijeet141/CropForesight-FrontEnd#187]
## Description

Currently, there are many files that contain unnecessary code and variables. Also in some places codes are repeated while they can be reduced using functions like map. You can see the warning of unused codes below:

<img width="759" alt="3" src="https://github.com/abhijeet141/CropForesight-FrontEnd/assets/86224794/9baf9be8-0fab-40fe-aab8-3f75948397f8">

I will make changes to fix this and try to follow the DRY (Don't repeat yourself) principle. This will make our codebase more managed and well-written.

**Comment by abhijeet141** [comment]
Hi @AlfiyaSiddique 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by AlfiyaSiddique** [comment]
Hello @abhijeet141 
I have been refactoring the code and found that the API key is visible for weather API. We can hide it using dotenv and environment variables. And by adding the environment variable in deployment. 

What do you say?

**Comment by AlfiyaSiddique** [comment]
@abhijeet141  ??

**Comment by AlfiyaSiddique** [comment]
@abhijeet141  please reply to the above query.
