### ISSUE TITLE
Improve the weather page

### ISSUE THREAD

**Issue by Piyusharora2003** [abhijeet141/CropForesight-FrontEnd#191]
The Ui if the weather page is very simple, i would like to add animations and better Ui to make the page more attractive, please assign me this task under GSSOC'23.

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/74443858/4d7912df-1aa3-4240-8f01-6fcc91258646)

**Comment by abhijeet141** [comment]
Hi @Piyusharora2003 
Thank you for creating the issue but the similar issue is already created if there will be no response i will assign the issue to you
