### ISSUE TITLE
Improve the Ui of the Example(Find your crop) page

### ISSUE THREAD

**Issue by Piyusharora2003** [abhijeet141/CropForesight-FrontEnd#192]
I see that there is a list on the Example page which is made very simple and also, the image hover effect makes image so big that it comes in other crops data, which looks odd, I would like to better the Ui of this page.

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/74443858/3ec084e5-4669-45bd-a6a5-b7dfa91aa38b)

Please assign me this task.

**Comment by abhijeet141** [comment]
Hi @Piyusharora2003 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by Piyusharora2003** [comment]
Thanks @abhijeet141 for such a warm response, i had made suffice changes .
As i am well aware that the dark mode is about to come in the site and the current color scheme make it difficult to made significant changes in the site . 
Here is the best i could come up with 

In hover on item state-
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/74443858/c74b07bd-2565-45a5-909b-073a1a2fd5f4)

Normal state-
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/74443858/23da971d-46aa-41ea-a257-d6bff4ac3978)

- [x] The animations are made smmoth
- [x] The theme of site is well maintained 
- [x] minimilistic , accurate changes made in the code.

**Comment by Piyusharora2003** [comment]
@abhijeet141  I have created a pull request regarding this task, please verify and merge it.
