### ISSUE TITLE
About page card

### ISSUE THREAD

**Issue by BhartiNagpure** [abhijeet141/CropForesight-FrontEnd#198]
On about page there is need to make card of technology, Agronomy and valuable insights .
I would like to make card of this and apply hover effect on it please assign me this issue.

**Comment by abhijeet141** [comment]
Hi @BhartiNagpure 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
