### ISSUE TITLE
Add a redirect link to Home page on Crop recommendation page

### ISSUE THREAD

**Issue by Vedant-MAHAjan** [abhijeet141/CropForesight-FrontEnd#2]
There is no button to return to the homepage from the crop recommendation page

**Comment by abhijeet141** [comment]
Hi @Vedant-MAHAjan 
Thank you for creating the issue. I have reviewed it, and it looks like a great opportunity to contribute. While we don't have a formal assignment process in place at the moment, you can definitely start working on it.

If you have any questions or need any assistance along the way, please don't hesitate to ask.

Thank you for your contribution, and I look forward to seeing your progress on resolving the issue.

**Comment by Vedant-MAHAjan** [comment]
Sure, I'll start working right away!

**Comment by vikaskumar2703** [comment]
close this issue @abhijeet141 if completed
