### ISSUE TITLE
Responsiveness for about page 

### ISSUE THREAD

**Issue by I-shika** [abhijeet141/CropForesight-FrontEnd#201]
I want to rectify responsiveness for about page as the page is not responsive.
![Screenshot (113)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/100770197/daad8429-e478-4687-8e42-d955def26761)
![Screenshot (114)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/100770197/4ccd34ad-0cb8-43f6-a21f-8bb8674fe217)

Please assign this issue to me under GSSoC'23.

**Comment by abhijeet141** [comment]
Hi @I-shika 
Thank you for creating the issue but the similar issue is already assigned
