### ISSUE TITLE
rectify Responsiveness for faq 

### ISSUE THREAD

**Issue by I-shika** [abhijeet141/CropForesight-FrontEnd#202]
I want to rectify responsiveness for faq page. as the recent ui is not looking good.
![Screenshot (115)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/100770197/51e4fea7-f703-42b0-ab8d-2bd2862608fd)

please assign this issue to me under GSSoC'23.

**Comment by abhijeet141** [comment]
Hi @I-shika 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
