### ISSUE TITLE
[Enhancement]:Improving Weather Section

### ISSUE THREAD

**Issue by vaibhavi-d18** [abhijeet141/CropForesight-FrontEnd#204]
The current weather section lacks user-friendliness , is not aligned with the website theme, and lacks responsiveness. Improving these aspects will create a more intuitive and visually appealing experience for users. 

@abhijeet141 could you please assign this to me under GSSoC'23

**Comment by abhijeet141** [comment]
Hi @vaibhavi-d18 
Thank you for creating the issue but some issue are already present and assigned on the responsiveness of weather section
