### ISSUE TITLE
[GSSOC'23]Website Display Issue on Mobile: Lack of Adaptive Flex Display and Misaligned UI

### ISSUE THREAD

**Issue by Tarun0951** [abhijeet141/CropForesight-FrontEnd#21]
**DESCRIPTION:-**
 It appears that the website lacks adaptive flex display functionality, resulting in a broken layout when the screen orientation changes.
**Here are some images from mobile**

![Screenshot_2023-05-26-13-34-49-547-edit_com android chrome](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/113555184/9192da50-15f9-4219-b225-61d995d1a1a1)

Please assign me this issue to fix this  under gssoc' 23

**Comment by akuldeepj** [comment]
I think its a tablet

**Comment by akuldeepj** [comment]
ya I just checked it. It breaks in tablets

**Comment by Tarun0951** [comment]
> ya I just checked it. It breaks in tablets

Yeah

**Comment by abhijeet141** [comment]
Hi @Tarun0951 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by abhijeet141** [comment]
Great Work 🚀
