### ISSUE TITLE
Improve Testimonial card in about us section 

### ISSUE THREAD

**Issue by Prajwal0225** [abhijeet141/CropForesight-FrontEnd#210]
**The Testimonials card looks to dull**

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/103810119/a6a12ac0-508d-4a01-a080-4a33d8bde5e8)

I would like to improve it.

**Comment by abhijeet141** [comment]
Hi @Prajwal0225 
Thank you for creating the issue but the similar issue is already assigned
