### ISSUE TITLE
feat: New weather card UI

### ISSUE THREAD

**Issue by rishuraj1** [abhijeet141/CropForesight-FrontEnd#226]
We might want to add the weather card to make it more attractive and user friendly.

I want the card to look something like this:

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/47839626/e4fcc0f2-c499-489f-9be2-c8bdd05d6204)

for reference:

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/47839626/79a3166d-5231-4363-ae9d-4ae3a0ace787)

Please assign this task to me under GSSoC '23. Thank You !

**Comment by abhijeet141** [comment]
Hi @rishuraj1 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
