### ISSUE TITLE
Alignment of search input

### ISSUE THREAD

**Issue by krutikajichkar** [abhijeet141/CropForesight-FrontEnd#229]
write now search input is aligned at left with some background color that doesn't suits UI . Also it is not responsive , I want to fix that , Please assign me this under gssoc'23

![Screenshot (152)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/93243210/b14804d2-1bc8-40e6-ad04-6392dc39b66c)
![Screenshot (151)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/93243210/eded4752-f28e-4845-9601-b5fc9cc267dc)

**Comment by abhijeet141** [comment]
Hi @krutikajichkar 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
