### ISSUE TITLE
Ui responsiveness for contact page 

### ISSUE THREAD

**Issue by I-shika** [abhijeet141/CropForesight-FrontEnd#234]
I want to make ui of contact page responsive as of now it is not responsive.
![Screenshot (138)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/100770197/12ad0f2a-ac48-4552-9a3e-63e714fa91ae)

![Screenshot (140)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/100770197/fa92e94b-1336-4812-ad19-0fea915690d3)

![Screenshot (139)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/100770197/6d1ca6bb-f712-4067-9880-f77433188d0f)

Please assign this issue to me under GSSoC'23.

**Comment by abhijeet141** [comment]
Hi @I-shika 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
