### ISSUE TITLE
Fix the improper align and improve the input section

### ISSUE THREAD

**Issue by akanksha984** [abhijeet141/CropForesight-FrontEnd#235]
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/97845909/14861216-4302-4500-ae60-8fbaf8415220)

I would like to fix the improper alignment of the search bar also I would like to enhance it. Make it look good
Please assign it to me under gssoc'23

**Comment by abhijeet141** [comment]
Hi @akanksha984 
Thank you for creating the issue but this issue is already assigned
