### ISSUE TITLE
Improve the testimonial section

### ISSUE THREAD

**Issue by akanksha984** [abhijeet141/CropForesight-FrontEnd#238]
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/97845909/c7f69faa-56a7-4ae9-9604-7f52781d570a)

I would like to improve the testimonial section. Please assign it to me under gssoc'23. I want to work on this issue.

**Comment by abhijeet141** [comment]
Hi @akanksha984 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
