### ISSUE TITLE
UPDATE README

### ISSUE THREAD

**Issue by Shikhar9425** [abhijeet141/CropForesight-FrontEnd#240]
wants to add more features other than that you have mentioned.
wants to add some more content to the description so that it will be more easily understandable.
align/modify some of the headings .
wants to make an impressive readme

**Comment by Shikhar9425** [comment]
@abhijeet141 please assign me this issue

**Comment by abhijeet141** [comment]
Hi @Shikhar9425 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
