### ISSUE TITLE
Find Your Crop Search is not properly align

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight-FrontEnd#242]
Hey, the Find your crop search bar is not aligned correctly. Also, If there is no matching I want to add some text.
Can you please assign it to me?

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/50cde0b3-1292-453b-a80f-45c5c67cb8a5)

**Comment by abhijeet141** [comment]
Hi @SubhamB2003 
Thank you for creating the issue but the similar issue is already assigned
