### ISSUE TITLE
[Enhancement]: Improve our contributors section 

### ISSUE THREAD

**Issue by dheeraj1129** [abhijeet141/CropForesight-FrontEnd#246]
I went to improve the contribution section list, adding some margin and some Animation with a hover effect on the button

![Screenshot (76)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/72201773/b2908854-c87e-4da9-97b4-e0f8a92ecace)

**Comment by abhijeet141** [comment]
Hi @dheeraj1129 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by dheeraj1129** [comment]
ok
