### ISSUE TITLE
Improvement of UI in weather page

### ISSUE THREAD

**Issue by muskandn** [abhijeet141/CropForesight-FrontEnd#247]
Currently the background of the Weather page is looking blank. Adding the world map in the background with low opacity can make it look more professional.  

This can be an example of what I am talking about.
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/99585352/d3c1af68-bc65-4acc-8a19-25bb670901d7)
I will change the color theme accordingly.
Please assign this to me under GSSoC'23

**Comment by abhijeet141** [comment]
Hi @muskandn 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
