### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by Harshu467** [abhijeet141/CropForesight-FrontEnd#248]
As of now the input data is not handle properly. Any values are been given in fields and still getting answers.
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/89975347/85495bf0-53de-4afe-bdc0-3ac5411dc0e1)

As seen in photo it is not giving any errors , it is important to handle error

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/89975347/bc6627b5-7821-44e2-870f-0ef65b0dfffa)
 Given these output on above input which is ilogical

**Comment by Harshu467** [comment]
Assign it to me

**Comment by abhijeet141** [comment]
Hi @Harshu467 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by Harshu467** [comment]
This is has been resolved and merged successfully
