### ISSUE TITLE
Improve search bar

### ISSUE THREAD

**Issue by shraddha761** [abhijeet141/CropForesight-FrontEnd#250]
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/106100728/2f35264c-8714-40ad-9b4e-43164b0f8ed9)

the search look very uneasy to website. I'll decrease size of search bar and adjust properly
Assign this issue to me under GSSOC'23

**Comment by abhijeet141** [comment]
Hi @shraddha761 
Thank you for creating the issue but similar issue is already assigned
