### ISSUE TITLE
Auto Comment to improve user collabration

### ISSUE THREAD

**Issue by shraddha761** [abhijeet141/CropForesight-FrontEnd#251]
Auto comment feature will comment automatically while issue open , close and pr is raised , merged

Assign this issue to me under GSSOC'23

**Comment by abhijeet141** [comment]
Hi @shraddha761 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
