### ISSUE TITLE
Ui of the Find The Crop Search Bar

### ISSUE THREAD

**Issue by Tisha6661** [abhijeet141/CropForesight-FrontEnd#253]
The search bar is not aligned, also the Ui is very simple, the colors are not going with the site, I would like to enhance the Ui of the search bar.

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/98682478/1dc0b9cc-355c-4d0c-9cdd-166216ece1bc)

**Comment by abhijeet141** [comment]
Hi @Tisha6661 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by abhijeet141** [comment]
For allignment issue so only work on the UI
