### ISSUE TITLE
Cose button on Crop Foresight

### ISSUE THREAD

**Issue by Dimple-Choudhary** [abhijeet141/CropForesight-FrontEnd#258]
Adding the Close button on the crop foresight component will make it easy for the user to navigate to the home page .
Below is just example:-
![x button](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/96401557/f4cdd7e5-bb8d-4693-b457-97314bd774e7)
`It will look better than this`

@abhijeet141 will you assign me this issue under GSSOC'23?

**Comment by abhijeet141** [comment]
Hi @Dimple-Choudhary 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
