### ISSUE TITLE
Footer Addition

### ISSUE THREAD

**Issue by muskandn** [abhijeet141/CropForesight-FrontEnd#263]
Adding a footer to the website will make it look more professional and attractive.
Please assign this to me under GSSoS'23.

**Comment by abhijeet141** [comment]
Hi @muskandn 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
