### ISSUE TITLE
Form page is not responsive

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight-FrontEnd#267]
Hey, this form page is not responsive plus its UI is not good at mobile view. Can you please assign it to me?

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/221d5660-e6be-4c67-a7a4-d1c8a972a47f)

**Comment by abhijeet141** [comment]
Hi @SubhamB2003 thank you for creating the issue but as of now form page is responsive
