### ISSUE TITLE
Remove horizontal scrollbar from about page

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight-FrontEnd#268]
Hey, can you please assign it to me?

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/ad051f86-f158-461a-92d1-b94f8c38dfbe)

**Comment by abhijeet141** [comment]
Hi @SubhamB2003 
Thank you for creating this issue but as of now horizontal scrollbar is already removed
