### ISSUE TITLE
<Bug>: loading effect

### ISSUE THREAD

**Issue by dheeraj1129** [abhijeet141/CropForesight-FrontEnd#273]
If the website load the first time and click on any nav element the error (preloading screen) for a small time appears.
if click again it will not happen for that element until the website will not refresh or reload.

once click on all nav elements the error does not appear again. only after a refresh or reload time happens 

![Screenshot (97)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/72201773/4f644d4a-bebb-4759-a938-87ae1ce1a215)

**Comment by abhijeet141** [comment]
Hi @dheeraj1129 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by dheeraj1129** [comment]
Error fixed now
