### ISSUE TITLE
Redesigning the form 

### ISSUE THREAD

**Issue by Prajwal0225** [abhijeet141/CropForesight-FrontEnd#274]
This form needs redesigning we can modify it to look more visually appealing 

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/103810119/766cfd41-6095-471a-8f25-348daba25c6a)

I would like to work on this issue. So can you please assign this issue to me?

**Comment by abhijeet141** [comment]
@Prajwal0225 Thank you for creating this issue but the UI for contact us is changed now
