### ISSUE TITLE
Improvement in weather section 

### ISSUE THREAD

**Issue by Prajwal0225** [abhijeet141/CropForesight-FrontEnd#275]
Currently, weather section looks like this
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/103810119/639d50d0-1885-401f-b89b-a8083ca4d5de)

I can modify it to make it more attractive like this 
![weather](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/103810119/84cf18a9-55fd-4007-821c-516259d0d45d)

**Comment by abhijeet141** [comment]
Hi @Prajwal0225 
Thank you for creating this issue but the UI for weather has been changed now
