### ISSUE TITLE
<style>: Weather text is not visible 

### ISSUE THREAD

**Issue by dheeraj1129** [abhijeet141/CropForesight-FrontEnd#277]
The weather section text is not aligned properly in a small device, the text is not visible. 

![Screenshot (99)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/72201773/fe8d8d4b-a1b2-49be-a86c-8a5c8d3046a5)

**Comment by abhijeet141** [comment]
Hi @dheeraj1129 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by dheeraj1129** [comment]
The Problem is no longer Now
