### ISSUE TITLE
Bug: Find your crop not working when user input in capital letters

### ISSUE THREAD

**Issue by anshumanjaiswal** [abhijeet141/CropForesight-FrontEnd#278]
Hi @abhijeet141, I want to fix this bug. Please assign it to me under GSSOC'23.

![Screenshot (167)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/70937672/eb3f1d79-90bf-4574-acc7-f0603f11e66b)

**Comment by abhijeet141** [comment]
Hi @anshumanjaiswal 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
