### ISSUE TITLE
The hamburger icon doesn't look good on mobile devices.

### ISSUE THREAD

**Issue by crocmons** [abhijeet141/CropForesight-FrontEnd#280]
The hamburger icon doesn't look good on mobile devices. As a GSSOC23 contributor, could I help fix this issue?

![Screenshot (37)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/106610322/a01d5309-ae3d-42f1-bf2a-b9f79fd38b16)

**Comment by abhijeet141** [comment]
Hi @crocmons 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
