### ISSUE TITLE
Contact form doesn't get reset after send

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [abhijeet141/CropForesight-FrontEnd#281]
Contact form doesn't get reset after submitting the data.
I'd like to work on this. could you please assign this to me.?

**Comment by abhijeet141** [comment]
Hi @SoundaryaKoutharapu 
As the UI is changed for contact us check for the bug again if issue persists message me I will assign you this issue

**Comment by SoundaryaKoutharapu** [comment]
@abhijeet141 
yep, the issue still exists.
and also it is not showing any message after submit.

**Comment by abhijeet141** [comment]
@SoundaryaKoutharapu Okay then I am assigning this issue to you

**Comment by SoundaryaKoutharapu** [comment]
okay, I will start working on it

**Comment by SoundaryaKoutharapu** [comment]
@abhijeet141 
contact form is not wrapped in form tag.
I added. but it is changing the layout.
shall i make pull request.?
