### ISSUE TITLE
Contact Page UI Update -GSSOC'23

### ISSUE THREAD

**Issue by Tarun0951** [abhijeet141/CropForesight-FrontEnd#282]
**I have updated the whole ui of the page please look at this below image:**
**PLEASE ASSIGN ME THIS UNDER GSSOC'23** @abhijeet141 

<img width="916" alt="image" src="https://github.com/abhijeet141/CropForesight-FrontEnd/assets/113555184/a9fdc255-9c01-42ac-8bda-5f01d6b035fd">

**Comment by abhijeet141** [comment]
Hi @Tarun0951 Thank you for creating but the UI of contact us page has been updated
