### ISSUE TITLE
Improve the contributors page

### ISSUE THREAD

**Issue by karthiknadar1204** [abhijeet141/CropForesight-FrontEnd#285]
The current contributor's page looks robotic with barely anything and also the responsiveness is completely mesy on all the screen sizes, I would like to completely revamp the contributors page from scratch,  will try to add some additional styling by adding better border effects to the cards and some overlay transition hover effects to the buttons on the cards and a new button to view the contribution log to the project.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by abhijeet141** [comment]
Hi @karthiknadar1204 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
