### ISSUE TITLE
Add github issue templates

### ISSUE THREAD

**Issue by karthiknadar1204** [abhijeet141/CropForesight-FrontEnd#287]
Would like to implement github actions to implement a proper workflow by creating issue templates for different categories and automate the process of making temporary labels on selecting an issue

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by abhijeet141** [comment]
Hi @karthiknadar1204 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
