### ISSUE TITLE
Search Bar Algorithum improvement 

### ISSUE THREAD

**Issue by Tisha6661** [abhijeet141/CropForesight-FrontEnd#290]
Bug:  
The current searchbar algorithum is very basic and not that useful in real life  and is only considering the season data 
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/98682478/d4e928ca-c55b-438f-9cff-f84fe0584ead)
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/98682478/d3700047-9cee-4c6e-9332-e80edb9e8623)
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/98682478/2465cc07-eee2-469e-ac89-a0ad3328c76a)

As we can see the search algorithum should be improved.
Idea: 
    I would like to work on this issue as a part of GSSOC 2023 , i can provide a more reliable approach to the problem by building an algorithum which finds the most suitable search items rearranged according to the asked ,  rather then just matching the name .

**Comment by abhijeet141** [comment]
Hi @Tisha6661 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
