### ISSUE TITLE
Login page creation using React JS with Regex Validation

### ISSUE THREAD

**Issue by GiriprasadKrishnamurthy** [abhijeet141/CropForesight-FrontEnd#291]
@abhijeet141 Could you please assign me this issue

**Comment by abhijeet141** [comment]
Hi @GiriprasadKrishnamurthy 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by GiriprasadKrishnamurthy** [comment]
Please accept and merge it into the main branch Si rplease

**Comment by GiriprasadKrishnamurthy** [comment]
@abhijeet141 Please merge my pull request for this issue

**Comment by GiriprasadKrishnamurthy** [comment]
@abhijeet141 Could you please check the Pull Request
made Sir only 4 days of coding period are remaining

**Comment by GiriprasadKrishnamurthy** [comment]
Sir Could you please merge the pull request for login form Please there are
only 4 days of coding period remaining I also want to contribute one more
to your repository after you merge this

**Comment by GiriprasadKrishnamurthy** [comment]
Sir could please check the Pull Request Made Sir

**Comment by GiriprasadKrishnamurthy** [comment]
Sir pls review the pull request Sit

**Comment by GiriprasadKrishnamurthy** [comment]
Pls Sir @abhijeet141/CropForesight-FrontEnd
***@***.***>
