### ISSUE TITLE
Adding more crops in find crop section

### ISSUE THREAD

**Issue by Swapnil-2503** [abhijeet141/CropForesight-FrontEnd#293]
There are many crops which are important to show, Also there we can hyperlink to show crop information

**Comment by abhijeet141** [comment]
Hi @Swapnil-2503 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
