### ISSUE TITLE
Contributor Section Issue

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [abhijeet141/CropForesight-FrontEnd#296]
Hello @abhijeet141 ,
The page is not aligned in the center.
### Screenshot -
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/121503426/3bbef68c-2440-4d65-aac6-df90255201e1)

**Comment by abhijeet141** [comment]
@SyedImtiyaz-1 From next time wait for the assignment and then only create a PR
