### ISSUE TITLE
contributor card and color

### ISSUE THREAD

**Issue by BhartiNagpure** [abhijeet141/CropForesight-FrontEnd#297]
I would like to reduce card margin on contributor page.
There is need to give top margin to contact us form.
also on home page there is border box to card crop name and testimonial want to remove as it not looks good
![Screenshot 2023-08-02 142154](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/104631882/5eceb5c7-c2e9-43fd-85aa-2843bfa51d1b)
![Screenshot 2023-08-02 141934](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/104631882/e4933481-abd9-4e59-8d7b-11674bd5bece)
.

**Comment by abhijeet141** [comment]
Hi @BhartiNagpure Thank you for creating this issue but the UI of contact us is already changed
