### ISSUE TITLE
Add PWA

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight-FrontEnd#301]
@abhijeet141 Hey, I want to add PWA (Progressive Web App). It was a very good feature as also convert to a native app. Can you please assign it to me?

**Comment by abhijeet141** [comment]
Hi @SubhamB2003 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
