### ISSUE TITLE
[BUG] The images in the Example section are hazy.

### ISSUE THREAD

**Issue by ManishaSwain8** [abhijeet141/CropForesight-FrontEnd#302]
The images opacity have been decreased,that is why the images are hazy  .It is making the page look very unattractive.We need to change it so that the images looks clear.

before:

![Screenshot (126)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/96622693/522301db-aa7f-4e97-8f18-a600c3a7855a)

after:
![Screenshot (127)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/96622693/11f20425-43a2-4eec-bb90-eef36116491d)

If this changes req. do assign under GSSOC 2023.

**Comment by abhijeet141** [comment]
Hi @ManishaSwain8 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
