### ISSUE TITLE
Predict your crop text not visible

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight-FrontEnd#303]
Predict your crop section text is not properly visible. Can you please assign it to me?

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/a3b0de9f-ecfd-4dc6-aeb8-228e891c0766)

**Comment by abhijeet141** [comment]
Hi @SubhamB2003 Thank you for creating this issue but now it is visible
