### ISSUE TITLE
JS validation add on contact form 

### ISSUE THREAD

**Issue by Geeta259** [abhijeet141/CropForesight-FrontEnd#305]
Empty field validation add on contact form
Error message shown below of each field
![Screenshot (53)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/75520947/c99d8b62-d060-4eb4-8cd3-1617c40d2358)

I did it before but it seems like it's not working .
@abhijeet141 I would like to again work on it please assign this to me.

**Comment by abhijeet141** [comment]
Hi @Geeta259 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
