### ISSUE TITLE
Contact Page UI/UX Upgraded 

### ISSUE THREAD

**Issue by thestarsahil** [abhijeet141/CropForesight-FrontEnd#306]
**This Is the New Contact Us Page** 

![Green and White Photographic Blogger Bio-Link Website](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/84167034/3cb4a8f0-0a60-4d93-bd18-0ee511034573)

I Found Some Bugs on Previous Contact Us page :
**1.Not Responsive 
2. Unhealthy Looking 
3. Implemention Structure Coding** 
![Crop-Predictor](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/84167034/67293be8-0795-405e-b85d-a8ed802a1df8)

**Please Assign Me Under GSSoc'23 , I shall be done this work in 1single day 
I am looking forward to you** 
@abhijeet141

**Comment by abhijeet141** [comment]
Hi @thestarsahil Thank you for creating this issue but the Contact Us UI has already been changed

**Comment by thestarsahil** [comment]
Can I work on responsive
Web and Android?
