### ISSUE TITLE
About page is not responsive

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight-FrontEnd#308]
@abhijeet141 Can you please assign this issue ?

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/9cb3d243-fcce-42a8-a50d-03432d5e9ad4)

**Comment by abhijeet141** [comment]
@SubhamB2003 It is happening because of a merged PR the contributor is working to fix the issue if he will not be able to fix this I will assign this to you

**Comment by SubhamB2003** [comment]
@abhijeet141 Still it's not fixed.
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/55ebd957-cc02-4e7c-ba9f-581a54c284f5)
