### ISSUE TITLE
Login page is not responsive

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight-FrontEnd#309]
Can you please assign this issue?

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/f6430259-7205-47d9-821b-7825f24706cf)

**Comment by abhijeet141** [comment]
Hi @SubhamB2003 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
