### ISSUE TITLE
About us page better UI

### ISSUE THREAD

**Issue by Sameep002** [abhijeet141/CropForesight-FrontEnd#31]
About us page need some alignments and will add a slideshow of actual images of website pages(like landing page, predict crop page and the result box) instead of just one static image

**Comment by abhijeet141** [comment]
Hi @Sameep002 
Thank you for creating the issue but this issue is already assigned https://github.com/abhijeet141/CropForesight/issues/47
If you want you can just add slideshow of images for this issue. If yes you can message me I will assign you this issue.

**Comment by Sameep002** [comment]
Hi @abhijeet141 yes will work that!!

**Comment by abhijeet141** [comment]
Great 🚀
