### ISSUE TITLE
[Page Upgrade] : Login

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [abhijeet141/CropForesight-FrontEnd#315]
Hello @abhijeet141 ,
I would love to contribute on the login page. 
I can make this better.
### Screesnhot - 
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/121503426/215c197d-7e84-403b-9006-a18ea23b09dc)

**Comment by SyedImtiyaz-1** [comment]
@abhijeet141

**Comment by abhijeet141** [comment]
Hi @SyedImtiyaz-1 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
