### ISSUE TITLE
[ANIMATION] Adding animation to the contributor page.

### ISSUE THREAD

**Issue by ManishaSwain8** [abhijeet141/CropForesight-FrontEnd#317]
It will be cool if we add some to cool animation in website which will make it look more attractive and alive.
And as the website is in react ,using Framer Motion is best choice. Adding animation to contributor page where all the contributor will appear one after another with smooth animation and flow.
If this feature req. do assign GSSOC 2023.  : |)

**Comment by abhijeet141** [comment]
Hi @ManishaSwain8 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
