### ISSUE TITLE
Weather Card Bug Fixed 

### ISSUE THREAD

**Issue by thestarsahil** [abhijeet141/CropForesight-FrontEnd#318]
**Before :** 
The Major problem is Container does'nt expand  from height while the content inside container expandes
So Added the Changes and Fixed this, and working for all location 
![Crop-Predictor2](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/84167034/e6f65c45-9108-4d58-8c19-6006b5ac16f8)

**After Implementing :**

![Crop-Predictor3](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/84167034/82cdcfcd-dcfa-44aa-9c1c-d6ed168e0d96)

Please Assign Me this under GSSoc23 , I'll have a Make PR 
@abhijeet141

**Comment by abhijeet141** [comment]
Hi @thestarsahil 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by thestarsahil** [comment]
I created a Pull Request 
https://github.com/abhijeet141/CropForesight-FrontEnd/pull/323

Please have a review on it
