### ISSUE TITLE
Adding code of conduct 

### ISSUE THREAD

**Issue by mohit-dhote** [abhijeet141/CropForesight-FrontEnd#321]
We propose adding a comprehensive Code of Conduct to our repository to ensure a safe, respectful, and inclusive environment for all contributors and users. This code will serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a wider range of perspectives.

I want to work on this issue under GSSOC23, kindly assign this to me @abhijeet141 Thank You !

**Comment by abhijeet141** [comment]
Hi @mohit-dhote 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by mohit-dhote** [comment]
I have created the PR kindly review it @abhijeet141 ! thank you
