### ISSUE TITLE
Password Reset Option Using Node JS and React JS update it to existing Login Page 

### ISSUE THREAD

**Issue by GiriprasadKrishnamurthy** [abhijeet141/CropForesight-FrontEnd#322]
Please assign this issue @abhijeet141

**Comment by GiriprasadKrishnamurthy** [comment]
I shall complete before the Coding Period Pls Assign ME this Sir @abhijeet141

**Comment by abhijeet141** [comment]
Hi @GiriprasadKrishnamurthy 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
