### ISSUE TITLE
Contact page form improvement

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight-FrontEnd#326]
Hey, I want to improve the contact page UI. Can you please assign it to me?

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/94003231/23d482ff-2bda-4ea9-969f-e53d2e2cff97)

**Comment by abhijeet141** [comment]
@SubhamB2003 UI looks fine for now you can work on making it mobile responsive

**Comment by SubhamB2003** [comment]
> @SubhamB2003 UI looks fine for now you can work on making it mobile responsive

Can you please assign it to me so I can make it responsive?

**Comment by SubhamB2003** [comment]
@abhijeet141 I want to make it responsive can you reopen this issue please
