### ISSUE TITLE
Remove gap in Contributors card

### ISSUE THREAD

**Issue by Prajwal0225** [abhijeet141/CropForesight-FrontEnd#335]
The cards are not properly centered soma extra gap is there from the left side

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/103810119/4d261216-6a72-49ce-98ed-f24fea4115df)

**Comment by abhijeet141** [comment]
Hi @Prajwal0225 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
