### ISSUE TITLE
Improve testimonials section 

### ISSUE THREAD

**Issue by Prajwal0225** [abhijeet141/CropForesight-FrontEnd#338]
Currently testimonials section is looking like this:
![IMG20230808140414.jpg](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/103810119/e2d9b539-2680-4686-818f-96eafe1eea52)

Arrows are not centred and left side arrow is overlapping with testimonial card

**Comment by abhijeet141** [comment]
Hi @Prajwal0225 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
