### ISSUE TITLE
Font color is not visible in Prediction Form

### ISSUE THREAD

**Issue by Mridul-2003** [abhijeet141/CropForesight-FrontEnd#34]
![Screenshot 2023-05-29 at 1 10 25 PM](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/110475111/85bceaef-567f-4ff2-9621-8af039274195)
Plz assign me this issue , I change the font color ....

**Comment by Palakkgoyal** [comment]
If somehow @Mridul-2003 is not available for this issue then, please assign this to me
