### ISSUE TITLE
Contact Page is not Responsive & Overflow

### ISSUE THREAD

**Issue by crocmons** [abhijeet141/CropForesight-FrontEnd#346]
Want to fix this issue kindly assign this issue to me as a GSSOC23 contributor
![Screenshot (55)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/106610322/3a8bb9ea-bbd9-4e80-9679-fa5de78f3168)

**Comment by abhijeet141** [comment]
Hi @crocmons 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
