### ISSUE TITLE
Adding Placeholders in contact page

### ISSUE THREAD

**Issue by krutikajichkar** [abhijeet141/CropForesight-FrontEnd#349]
Placeholders are not there in contact input , i want to add them , please assign me this under gssoc'23
![Screenshot (218)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/93243210/f3535de1-4a74-41af-b98c-811a0205631d)

**Comment by krutikajichkar** [comment]
@abhijeet141 please assign me this

**Comment by abhijeet141** [comment]
Hi @krutikajichkar 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
