### ISSUE TITLE
Missing Placeholder in Login

### ISSUE THREAD

**Issue by krutikajichkar** [abhijeet141/CropForesight-FrontEnd#351]
I want to add placeholders in Login , please assign me this under gssoc'23

![Screenshot (219)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/93243210/623fdd59-508c-4ed3-b74b-91a89499f225)

**Comment by abhijeet141** [comment]
Hi @krutikajichkar 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
