### ISSUE TITLE
Darkmode is not working in some pages

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [abhijeet141/CropForesight-FrontEnd#353]
@abhijeet141 
Here is a video of the issue that the darkmode is not working proeprly 
[Screencast from 09-08-23 12:39:28 PM IST.webm](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/121503426/0405f70b-68ec-4a50-9104-7c3ce3337d00)

**Comment by abhijeet141** [comment]
Hi @SyedImtiyaz-1 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by NamandeepNegi** [comment]
@abhijeet141  assign this issue to me

**Comment by SyedImtiyaz-1** [comment]
@abhijeet141 Assign this to @NamandeepNegi I'm busy currently.

**Comment by NamandeepNegi** [comment]
@abhijeet141 assign this issue to me please
