### ISSUE TITLE
[gssoc'23] Spelling Mistake in the Text

### ISSUE THREAD

**Issue by Tarun0951** [abhijeet141/CropForesight-FrontEnd#36]
**DESCRIPTION:-**
Predicting is written as pridicting the best crop 
<img width="285" alt="image" src="https://github.com/abhijeet141/CropForesight-FrontEnd/assets/113555184/447c4009-5386-41be-9b17-e9aa803a9e1a">
**PLEASE  ASSIGN ME THIS ISSUE TO CORRECT**

**Comment by abhijeet141** [comment]
Hi @Tarun0951 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
