### ISSUE TITLE
title  border and padding

### ISSUE THREAD

**Issue by BhartiNagpure** [abhijeet141/CropForesight-FrontEnd#361]
On home page there is need to give padding as it touch to page .
also need to remove border of cropname on card as it not looks good.
![Screenshot 2023-08-09 143604](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/104631882/d6a1a50a-5dc9-4789-aee5-ffe66628af41)

**Comment by abhijeet141** [comment]
Hi @BhartiNagpure 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
