### ISSUE TITLE
loading and error handling in REST API

### ISSUE THREAD

**Issue by NamandeepNegi** [abhijeet141/CropForesight-FrontEnd#369]
loading and error handling not working properly with REST API of evaluating,  it also require some conditional checkes.

**Comment by NamandeepNegi** [comment]
assign it to me @abhijeet141

**Comment by abhijeet141** [comment]
Hi @NamandeepNegi 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by abhijeet141** [comment]
@NamandeepNegi  Are you working under GSSOC ?

**Comment by NamandeepNegi** [comment]
No, I am not @abhijeet141

**Comment by abhijeet141** [comment]
@NamandeepNegi Okay !

**Comment by NamandeepNegi** [comment]
issue resolved in pull request #366
