### ISSUE TITLE
[FEAT] Dockerizing the app

### ISSUE THREAD

**Issue by Viveksati5143** [abhijeet141/CropForesight-FrontEnd#370]
Creating Dockerfile & .dockerignorefile for the app

**Comment by Viveksati5143** [comment]
Hey @abhijeet141,
Can I work on this feature as my first issue in this repo?
Creating a Dockerfile would help anyone to run the project in their local environment.
Thanks

**Comment by abhijeet141** [comment]
Hi @Viveksati5143 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
