### ISSUE TITLE
[FEAT] Making the contributors section dynamic

### ISSUE THREAD

**Issue by Viveksati5143** [abhijeet141/CropForesight-FrontEnd#371]
The svg in readme.md will look something like this with limit upto 54 contributors & will move from right to left.
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/100852245/1bd16176-b12b-4a60-8ef0-3a203af6ab29)

**Comment by Viveksati5143** [comment]
Hey @abhijeet141 
Please assign me this issue under gssoc
Thanks

**Comment by abhijeet141** [comment]
Hi @Viveksati5143 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
