### ISSUE TITLE
The Testimonials design needs to be fixed

### ISSUE THREAD

**Issue by nitin-pandita** [abhijeet141/CropForesight-FrontEnd#373]
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/91310284/634eefc1-0d2c-4f85-a35f-574e1566713e)

@abhijeet141  The Testimonials are way too big and need some styling, i can help you I fixing this issue.

**Comment by abhijeet141** [comment]
@nitin-pandita Thanks for creating the issue but this issue is fixed now
