### ISSUE TITLE
Weather page footer

### ISSUE THREAD

**Issue by BhartiNagpure** [abhijeet141/CropForesight-FrontEnd#376]
On weather page footer is collapse with page content.
I would like to fix it.
![Screenshot 2023-08-10 072339](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/104631882/c1d1a416-04f7-42c8-9570-f38ff433e5ba)

**Comment by abhijeet141** [comment]
Hi @BhartiNagpure 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
