### ISSUE TITLE
Add JS Validation on Contact Form

### ISSUE THREAD

**Issue by Geeta259** [abhijeet141/CropForesight-FrontEnd#38]
I want to add JS validation on Contact form to prevent from unwanted data.
1)Showing Error message on blank field  
2)Email validation

If any error occurs on particular field that field can be shown by red border to indicate  something happens wrong on that field.
![Screenshot (315)](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/75520947/1c8f6751-d287-4017-a063-01a62c1b8912)

Here is demo below:
![demoform](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/75520947/5603f6aa-a9fb-4b00-b639-ef4611f378db)

@abhijeet141 I want to contribute on this project by adding a validation in contact form to enhancing UI under GSSOC'23.

**Comment by abhijeet141** [comment]
Hi @Geeta259 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
