### ISSUE TITLE
Home Link is not visible behind the Circle 

### ISSUE THREAD

**Issue by nitin-pandita** [abhijeet141/CropForesight-FrontEnd#392]
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/91310284/963d2b60-d7f5-4079-864f-77b32acf8f88)

**Comment by abhijeet141** [comment]
Hi @nitin-pandita 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by nitin-pandita** [comment]
> Hi @nitin-pandita Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.
> 
> Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

Thanks
