### ISSUE TITLE
Unreadable home page

### ISSUE THREAD

**Issue by akuldeepj** [abhijeet141/CropForesight-FrontEnd#5]
@abhijeet141  I would like to work on the homepage for making the UI(button) better,make changes in the home to be more apeling and the text readable  as it is not having any different font from the video and it even overlaps with it and changing the button as it doesn't suit this background could you assign this task to me under GSSoC'23

![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/97216956/a580fc02-c42e-40a2-a9a5-10dcbde86d09)

**Comment by abhijeet141** [comment]
Hi @akuldeepj 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by akuldeepj** [comment]
@abhijeet141 what do you think of this design 
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/97216956/16f6f1c5-57ec-47dc-97c2-6f6bf8f120b5)
If you feel its good I would work on making it **responsive**
