### ISSUE TITLE
mis-alignment of website 

### ISSUE THREAD

**Issue by akuldeepj** [abhijeet141/CropForesight-FrontEnd#52]
hey @abhijeet141 the website has become misaligned with recent PR's I would like to fix it and also improve the responsiveness of the website

**Comment by abhijeet141** [comment]
Hi @akuldeepj 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

**Comment by akuldeepj** [comment]
hey @abhijeet141 is it ok if I also make the navbar collapsable in mobile view

**Comment by abhijeet141** [comment]
@akuldeepj Mistakenly I combined this issue with other PR therefore I am removing the level and reopening the issue.

**Comment by akuldeepj** [comment]
ok i will restart work on this soon

**Comment by akuldeepj** [comment]
progress made:
--made contact page responsive
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/97216956/215b4b2c-faf8-4e56-a68b-659bbeac4b92)
to be done:
--make weather page responsive
-- making navbar collapsable on mobile devices

**Comment by akuldeepj** [comment]
made weather page responsive for mobiles 
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/97216956/3e32e715-092b-4dc5-94bc-42e6fdd3a511)
