### ISSUE TITLE
[REQUEST] Contact us page - ui change #gssoc23

### ISSUE THREAD

**Issue by ritika1408** [abhijeet141/CropForesight-FrontEnd#63]
The contact us form's ui is unorgranized. I would like to make some formatting to that. And also the about us page's ui needs a little alignment. Please assign me the issue. I would be happy to contribute. #gssoc23

**Comment by abhijeet141** [comment]
Hi @ritika1408 
Thank you for creating this issue but there is already issue under which contributor is working on improving UI of contact-us.
