### ISSUE TITLE
Designing Adding responsiveness to form for all devices

### ISSUE THREAD

**Issue by tajmalnas** [abhijeet141/CropForesight-FrontEnd#7]
as of now it is not even looking good on laptop .So please assign this issue under me so that i can start working on it

**Comment by abhijeet141** [comment]
Hi @tajmalnas 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by tajmalnas** [comment]
Thank you

**Comment by tajmalnas** [comment]
added design pushed please check it
