### ISSUE TITLE
Make the website responsive for small screen

### ISSUE THREAD

**Issue by AyishikD** [abhijeet141/CropForesight-FrontEnd#72]
The website is not responsive for small screen. The weather button is getting hidden and the images are not coming properly.
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/99983449/27676cf7-0915-4d7f-9725-dc762915a2c6)
For 320*364 screen this error is coming. I want to fix it and make the site responsive.

**Comment by abhijeet141** [comment]
Hi @AyishikD 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
