### ISSUE TITLE
Improve the UI of the Weather page...

### ISSUE THREAD

**Issue by govardhan-26** [abhijeet141/CropForesight-FrontEnd#79]
Hello, I am in  GSSOC'23....

I want to add features in the weather page. Like It is giving the temperature but it isnt giving the scale in which the temperture is given. and also we can use some pics to say about the temperature like we can keep a sun pic if it is sunny and hot and clouds if it is cloudy based on the temperature. And we can improve the UI of the page.

I want to contribute on this. Please assign this issue to me.

**Comment by abhijeet141** [comment]
Hi @govardhan-26 , Thank you for creating this issue as contributors are working on refining the whole weather page once it is done and then you think of any changes I will assign this issue to you.
