### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by Krishnakalani111** [abhijeet141/CropForesight-FrontEnd#8]
Currently, the signup and signin pages on our platform lack proper form validation. To enhance the user experience and ensure accurate data input we need form-validation. For example PH level  range goes from 0 - 14. and as of now a user can enter ph level in negative as well as more then 14. Assign this issue to me under the label Gssoc'23 with the appropriate level, i want to work on this
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/88764668/bd7fb31e-a8b1-434a-89ad-5679bcda370b)

**Comment by abhijeet141** [comment]
Hi @Krishnakalani111 
Thank you for creating the issue a similar issue is already assigned https://github.com/abhijeet141/CropForesight_BackEnd/issues/1 if there will be no response than I will assign this issue to you.
