### ISSUE TITLE
Improving Contact page 

### ISSUE THREAD

**Issue by Owais24code** [abhijeet141/CropForesight-FrontEnd#81]
@abhijeet141 sir,
I am GSSOC 23 contributor.
I want to change the contact page UI listed as are idea 

- contact Us form should be in the center 
- better alignment of the form 
- footer where all social account logos are present 
![Screenshot 2023-06-21 205901](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/112776960/3a5f5e9f-7358-4155-9c21-22f3cae956d7)

**Comment by abhijeet141** [comment]
Hi @Owais24code , Thank you for creating this issue but this issue is already resolved.
