### ISSUE TITLE
Improving the UI of the About Page

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [abhijeet141/CropForesight-FrontEnd#83]
# Issue
I will be improving the UI of the About Page section
I will be proper alligning items on the page

# Screenshots
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/85278243/dac6cbed-f842-4c49-83e9-e2e97e4dbb21)

Please assign me this issue under GSSOC'23

**Comment by abhijeet141** [comment]
Hi @Swapnil-Singh-99 
Thank you for creating the issue but the similar issue is already assigned.
