### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Harshu467** [abhijeet141/CropForesight-FrontEnd#86]
Every Website has footer , without footer website cannot be standard This website need proper footer. Assign it to me, I can create better footer

**Comment by SaraKadam24** [comment]
I am already working on it (issue #66 )

**Comment by Harshu467** [comment]
@SaraKadam24  I want to work on it as well. u did not have label of level!

**Comment by abhijeet141** [comment]
Hi @Harshu467 Thank you for creating the issue but this issue is already assigned
