### ISSUE TITLE
Contact page bug

### ISSUE THREAD

**Issue by Soumyajit2825** [abhijeet141/CropForesight-FrontEnd#87]
![Screenshot 2023-06-21 172717](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/100519291/37a49cd6-845b-4653-810a-2bce3fe5924e)
<br>
As there you can see that the input fields are not right aligned 
I want to fix this bug
@abhijeet141

**Comment by abhijeet141** [comment]
Hi @Soumyajit2825 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue

**Comment by Soumyajit2825** [comment]
@abhijeet141 After how many days you're seeing my issue????
Is this issue still available??
Please check before assigning someone
And please response fast
