### ISSUE TITLE
Back to home button

### ISSUE THREAD

**Issue by Soumyajit2825** [abhijeet141/CropForesight-FrontEnd#88]
I want to add a back to home button in the "Crop Recommendation" page as there is no button to go back to the home page 

Here is the screen-shot
<br>
![Screenshot 2023-06-21 172905](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/100519291/fc95ff27-c6cc-4d10-acc3-bd58367b30e7)
<br>
@abhijeet141 I want to work in this issue

**Comment by abhijeet141** [comment]
Hi @Soumyajit2825 
Thank you for creating this issue but this issue is already assigned. 
https://github.com/abhijeet141/CropForesight/issues/90
