### ISSUE TITLE
Allign buttons and text box

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [abhijeet141/CropForesight-FrontEnd#90]
# Issue 
I will be alligning text box and button on the home page in a vertical manner and centering them

# Screenshots
![image](https://github.com/abhijeet141/CropForesight-FrontEnd/assets/85278243/f86d50f5-b348-4015-a331-03366722bd2c)

Please assign me this issue under GSSOC'23

**Comment by abhijeet141** [comment]
@Swapnil-Singh-99 Thank you for creating the issue but this issue is already resolved.
