### ISSUE TITLE
#IMPROVEMENT IN ALIGNMENT OF CONTACT PAGE AND ADDING SOME DESIGN IN IT 

### ISSUE THREAD

**Issue by adi10032003** [abhijeet141/CropForesight-FrontEnd#93]
Hello sir i want through your project and i am interested in making the changes in the contact page the changes that i am going to make is that 
1.Trying to make a good ui of it 
2.Will improve its alignment 
3.Adding show attractive design and improved responsiveness 
Please issue it to me under gssoc 
Will be waiting for your reply 
Thank You

**Comment by abhijeet141** [comment]
Hi @adi10032003 Thank you for creating this issue as this issue has been already resolved once check the page if you think you can add some other changes just ping me here I will assign this issue to you.

**Comment by adi10032003** [comment]
Thank you for your response i went through the contact page i found it better then the previous design i think that i can improve it and make it more effective so can u pls assign it to it me under gssoc
Thank you will be waiting for your reply
