### ISSUE TITLE
Website is not Responsive

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight-FrontEnd#94]
Hey, made a PR can you please check? I created this issue in your "CropForesight" repo and you assign this to me

**Comment by abhijeet141** [comment]
@SubhamB2003 This issue is already created by you in main repo no need to create another issue

**Comment by SubhamB2003** [comment]
> @SubhamB2003 This issue is already created by you in main repo no need to create another issue

Okk
