### ISSUE TITLE
Add a CodeQL Workflow

### ISSUE THREAD

**Issue by abhinav-m22** [abhijeet141/CropForesight-FrontEnd#95]
The repository has JavaScript code, but it lacks workflow for code inspection.

The codeql.yml workflow file will be added by me to automate security checks.

CodeQL is a code analysis tool, to find vulnerabilities in programs.
The code will be examined, and the results will be presented as code scanning alerts.
Every push, commit, and pull request that uses GitHub actions will have it enabled.

I want to work on this issue.
Please assign me the task under GSSoC'23.

**Comment by abhijeet141** [comment]
Hi @abhinav-m22 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
